# Generated by Django 4.1.6 on 2023-03-06 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_fullfillment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fullfillment_Date2',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 13, 2, 11, 464187)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fullfillment_Date',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 13, 2, 11, 464187)),
        ),
    ]
