# Generated by Django 4.1.6 on 2023-03-07 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_fullfillment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fullfillment_Date',
            field=models.DateField(default=datetime.datetime(2023, 3, 14, 20, 2, 41, 646914)),
        ),
    ]
